spring:
  datasource:
    url: jdbc:mysql://cdb-38tlc6lg.cd.tencentcdb.com:10086/market
    username: root
    password: acmketaihaowanle1+
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888

password-salt: 123456